////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= FrontJs Portal

Le composant frontJsPortal, inclus dans le plugin du même nom, a pour objectif de fournir un moyen de gérer l'interface utilisateur
avec une technologie de type FrontJs, c'est à dire VueJs, ou React ou Angular.

Il utilise, d'une part le systéme de portlet / portal de ofbiz, défini en XML, et un applicatif développé en javascript.

Pour l'instant ce composant est à l'état de POC (Proof Of Concept), c'est à dire que c'est un concrétisation de différentes idées
afin de pouvoir en discuter plus facilement. +
Il est développé dans un état d'esprit "Agile" c'est à dire que les résultats concrets sont privilégiés en acceptant de générer
une dette technique.  

La documentation qui suit a pour objectif, 

* d'une part d'expliquer où nous en est le composant et comment il fonctionne et quels sonts les points choisis et ceux laissés de coté
* d'autre part de préparer la futur documentation en détaillant les éléments à destination des futur utilisateurs

L'objectif majeur d'utiliser un framework javascript pour l'interface utilisateur est d'augmenter le nombre d'élément interactif 
dans les écrans, même quand les écrans sont construit / paramétré à partir de "module" existant en standard :

* mettre à jours une partie de l'écran en fonction d'une action ou d'une mise à jours de donnée;
* modification de formulaire en cours de saisi en fonction de la saisi des premmier champ;
* paramétrage simple d'un écran (page portal) sans avoir à se préoccuper de l'interaction entre portlet. 


include::_include/poc-vuejs_fr.adoc[leveloffset=+1]


== Portlet
[CAUTION]
Hypothèse à confirmer quand il y en aura besoin : +
Il faut pouvoir associer à la portlet le nom d'un (ou de plusieurs) identifiant/s correspondant à ce qui sera surveillé pour que 
la portlet se mette à jour. Par exemple, pour la portlet editExample, l'identifiant est exampleId. +
Quand cette portlet s'affiche pour la première fois via un showPortlet, si il y a un exampleId dans les data alors le champ
exampleId est créer, sur le client Js, avec sa valeur. +
...

=== Mise à jour Portlet
C'est la mise à jours de donnée au niveau du store du client Js qui déclanche la mise à jours de la portlet


== Portal Page

== Dev and prod

=== message de retour 

* _EVENT_MESSAGE_LIST_ : pour obtenir un event message list il faut; faire un creatExample ayant comme statusId="EXST_COMPLETE". 
* _EVENT_MESSAGE_ : pour obtenir un EventMessage il faut; faire un creatExample ayant comme statusId="EXST_APPROVED".
* _ERROR_MESSAGE_ : pour obtenir un ErrorMessage il faut; que le exampleTypeId et que le description soient null.
* _ERROR_MESSAGE_LIST_ : pour obtenir un ErrorMessage list il faut; que le exampleTypeId soit null.

== FrontJs Glossary

[CAUTION]
object2TrackId ou monitorName ou observerId ou trackerId ou ... +
c'est le nom du champ qui sert de déclancheur pour mettre à jour la portlet

[CAUTION]
DataView versus DataForm ou data versus html +
afin de pouvoir différentier dans les phrases parlant d'un flux entre serveur et client Js le type d'information reçu
ou traiter.


[#GENERICDATAVIEW]
GenericDataView:: C'est un objet stocker par le client Javascript (dans le store pour VueJs) correspondant à une GenericEntity au 
  niveau du serveur. Il contient les données affichées (ou présente dans le formulaire mais hidden) donc potentiellement différente
  de ce qu'il y a dans la GenericValue correspondante.




