////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= FrontJs Portal

Le composant frontJsPortal, inclus dans le plugin du même nom, a pour objectif de fournir un moyen de gérer l'interface utilisateur
avec une technologie de type FrontJs, c'est à dire VueJs, ou React ou Angular.

Il utilise, d'une part le systéme de portlet / portal de ofbiz, défini en XML, et un applicatif développé en javascript.

Pour l'instant ce composant est à l'état de POC (Proof Of Concept), c'est à dire que c'est un concrétisation de différentes idées
afin de pouvoir en discuter plus facilement. +
Il est développé dans un état d'esprit "Agile" c'est à dire que les résultats concrets sont privilégiés en acceptant de générer
une dette technique.  

La documentation qui suit a pour objectif, 

* d'une part d'expliquer où nous en est le composant et comment il fonctionne et quels sonts les points choisis et ceux laissés de coté
* d'autre part de préparer la futur documentation en détaillant les éléments à destination des futur utilisateurs

L'objectif majeur d'utiliser un framework javascript pour l'interface utilisateur est d'augmenter le nombre d'élément interactif 
dans les écrans, même quand les écrans sont construit / paramétré à partir de "module" existant en standard :

* mettre à jours une partie de l'écran en fonction d'une action ou d'une mise à jours de donnée;
* modification de formulaire en cours de saisi en fonction de la saisi des premmier champ;
* paramétrage simple d'un écran (page portal) sans avoir à se préoccuper de l'interaction entre portlet. 


include::_include/vu-intro_fr.adoc[leveloffset=+1]

== Choix pour le POC

Usage de la *branche trunk* de Apache OFBiz.

Usage des principes et architecture de *Portal Page et Portlet* de Apache OFBiz. 

Le *théme Rainbow Stone* a été retenu comme base pour le POC, il a été dupliqué dans le plugin rbstvuejs. +
Ce plugin introduits donc 4 nouveaux thèmes : Rainbow Stone Vuejs - xxxx. +
Les nouveaux thèmes sont dédiés pour l'usage de la webapp Portal, une grande partie des macro ftl de rendu de champ ont
été adapté en fonction des besoins.

L'ensemble des exemples d'usage sont *avec le composant example* et pendant la durée du POC même des fichiers qui devrait
être dans common sont mis dans example afin de simplifier l'installation et mise à jours.

Une *webapp supplémentaire exampleapi* a été créé pour centraliser les uri autorisé pour le composant vuejsPortal, 
c'est paramétré dans le fichier constantes.js.

En attendant le login par token dans ofbiz (cf https://issues.apache.org/jira/browse/OFBIZ-9833 ) le login actuel dans 
le composant portal (  https://localhost:8443/portal ) utilise le méchanisme *ofbiz standard de login via cookies* .

Les *screens, forms, menus* utilisés pour les portlets sont définis *en xml*.

La transmission des éléments d'affichage sont transmis à l'application FrontJs via les templates macro ftl de manière
à envoyer des *balises dédiées*, une par macro existante) ne comportant *que les paramètres*.
[source,xml]
----
<#macro renderDisplayField imageLocation alert type="" idName="" description="" title="" class="" inPlaceEditorUrl="" inPlaceEditorParams=""  <1>
 ><vue-label  <2>
          imageLocation="${imageLocation}" <3>
          alert="${alert}"
          type="${type}"
          idName="${idName}"
          description="${description}"
          title="${title}"
          class="${class}"
          inPlaceEditorUrl="${inPlaceEditorUrl}"
          inPlaceEditorParams="${inPlaceEditorParams}" /></#macro>
----
<1> La macro appelé par le rendrer
<2> La balise pour l'application VueJsPortal
<3> les paramètres qui ne sont transmit que si non null

Il y a *un composant (vuejs) par macro*.

Lors de la réception d'un flux en provenance d'un "screen" *un store est créé pour stocker* les données (exampleId, exampleName, ...),
nous l'appelons *GenericDataView*, elle correspond à une GenericEntity mais du cotè utilisateur. 

Le *showPortlet est redéfini* dans le POC par simplification, pour faire ce que l'on souhaite et seulement ça.

include::_include/poc-situation_fr.adoc[leveloffset=+1]

include::_include/poc-todo_fr.adoc[leveloffset=+1]

== Portlet
Il faut pouvoir associer à la portlet le nom d'un (ou de plusieurs) identifiant/s correspondant à ce qui sera surveillé pour que 
la portlet se mette à jour. Par exemple, pour la portlet editExample, l'identifiant est exampleId. Quand cette portlet s'affiche
pour la première fois via un showPortlet, si il y a un exampleId dans les data alors 


== Portal Page

== Dev and prod

== POC Glossary

[CAUTION]
object2TrackId ou monitorName ou observerId ou trackerId ou ... +
c'est le nom du champ qui sert de déclancheur pour mettre à jour la portlet

[CAUTION]
DataView versus DataForm ou data versus html +
afin de pouvoir différentier dans les phrases parlant d'un flux entre serveur et client Js le type d'information reçu
ou traiter.


[#GENERICDATAVIEW]
GenericDataView:: C'est un objet stocker par le client Javascript (dans le store pour VueJs) correspondant à une GenericEntity au 
  niveau du serveur. Il contient les données affichées (ou présente dans le formulaire mais hidden) donc potentiellement différente
  de ce qu'il y a dans la GenericValue correspondante.




