////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= POC Vuejs Portal

Actuellement le premier applicatif javascript permettant d'utiliser les portlets - portal Apache OFBiz est écrit avec
le framework VueJs.

Il a été choisi pour sa simplicité d'apprentissage et en raison du pilotage de son développement par une communauté plutôt
que par une société.

== Installation POC VuejsPortal

. à partir d'un ofbiz-framework (trunk) téléchargé à partir du svn (https://ofbiz.apache.org/source-repositories.html[documentation standard  SourceRepository]) 
  une version svn supérieur à  1837232
. créer le répertoire plugins dans ofbiz-framework
. télécharger, avec git, dans le répertoire plugins :
.. le plugin vuejsportal à partir du https://gitlab.ofbizextra.org/ofbizextra/ofbizplugins/vuejsPortal
.. le plugin example (de Apache OFBiz) modifié pour les besoins du POC à partir de https://gitlab.ofbizextra.org/ofbizextra/ofbizplugins/example
    et en se mettant sur la branch vuejsPortal
. Il faut ensuite modifier quelques fichiers dans ofbiz-framework. +
  Pour se faire, executer la commande suivante en étant positionné dans le repertoire 'plugins/VuejsPortal' : +
  `rsync -a --exclude-from=./ofbizFiles/rsyncExcludes ./ofbizFiles/ ../../` +
. Pour le build de l'applicatif vuejs il faut avoir nodejs installé sur son environement
.. Pour installer node.js dans un environnement debian, executer le commandes suivantes : +
`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -` +
`sudo apt-get install -y nodejs` +
Dans le cas d'un autre environnement veuiller consulter la page https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
.. en attendant une commande intégré à gradle
... il faut se positionner à la racine de la webapp vuejs 'plugins/vuejsPortal/webapp/vuejsPortal'
* `npm i`  <= pour charger toutes les dépendances
* `npm run build` <= pour builder
. il est maintenant possible de lancer ofbiz classiquement : +
`./gradlew cleanAll loadAll ofbiz` +
( à partir de la *racine de ofbiz-framework* )
. aller se connecter à l'application portal https://localhost:8443/exampleapi/control/main

== Choix pour le POC

Usage de la *branche trunk* de Apache OFBiz.

Usage des principes et architecture de *Portal Page et Portlet* de Apache OFBiz.

L'ensemble des exemples d'usage sont *avec le composant example* et pendant la durée du POC même des nouveaux fichiers qui devrait
être placé dans common sont mis dans example afin de simplifier l'installation et mise à jours.

Une *webapp supplémentaire exampleapi* a été créé pour centraliser les uri autorisé pour le composant vuejsPortal, 
c'est paramétré dans le fichier constantes.js. +
Le composant vuejsPortal n'est pas spécifique à un composant, il necessite juste une uri de base pour ses requêtes.
Cette uri est paramètré dans le fichier constantes.js pour l'instant, mais dans le futur le paramétrage sera plus souple
afin de pouvoir utiliser vuejsPortal avec plusieurs composants, y compris si cela doit apparaitre comme plusieur "webapp"
dans le menu utilisateur.

Le composant portal (  https://localhost:8443/exampleapi/control/login ) utilise le méchanisme *ofbiz standard de login via cookies*, 
il pourra par la suite utiliser le login par token de ofbiz (cf https://issues.apache.org/jira/browse/OFBIZ-9833 ).

Les *screens, forms, menus* utilisés pour les portlets sont définis *en xml*, et dans des fichiers dédiés pour plus de lisibilité.

Il y a *un composant (vuejs) par élément screen ofbiz* ( SingleItemRow => vue-single-item-row ), qui sont défini via les renderer au
niveau screen, form, menu (et pour les renderer html qui correspondent globalement au macro.ftl). Pour l'instant, pour le POC,
pour avoir la liste, il faut faire une recherche sur les appels `ouput.*Screen(` . 

=== Balise XML utilisé
Pendant le POC, aucune nouvelle property ou balise XML n'est ajouté mais à l'opposé certaine balise ou property
sont détournés pour des usages VueJs exclusif.

* screen
  ** dans la balise `<container`, `auto-update-target` est utilisé pour le nom du watcher associé à ce container 
* form
  ** dans la balise `<on-event-update-area` 
    *** `area-target` +
         = 'a' implique que l'ensemble des champs du formulaire sont transmit au watcher, et donc pris en compte
         lors du déclanchement du rafraichissement afférant. +
         = 'p' indique que seul les paramètre du on-event-update-area sont pris en compte.
    *** `area-id` correspond au nom du watcher qui doit être mis à jour
  ** dans la balise `<hyperlink`
    *** `link-type="anchor"` est utilisé pour signifier que c'est un appel interne FrontJs
    *** `target-window` est utilisé pour désigner le nom du watcher qui doit être mis à jours
* menu
  ** dans la balise `<link` 
    *** `link-type="anchor"` est utilisé pour signifier que c'est un appel interne FrontJs
    *** `target-window` est utilisé pour désigner le nom du watcher qui doit être mis à jours

=== Renderer FrontJs
Un *nouveau viewHandler* ainsi qu'un nouvel ensemble de *renderer* a été créé. +
Un nouveau package à été créé dans org.apache.ofbiz.widget.renderer frontJs qui contient l'ensemble des nouveaux renderer.

Dans ce package, il y a une class FrontJsOutput qui permet de construire les éléments nécessaires au format de sortie souhaité.
Un objet de cette class est instancié en début de traitement du viewHandler, puis est compléter par les appels a chacun des objet renderer.

L'uri *showPortletFj* du composant exampleApi utilise le nouveau viewHandler pour retourner le resultat du rendu du screen, showPortlet.

cette uri est utilisé par l'applicatif vueJs pour toutes les requêtes de récupération des informations d'affichage. +
Le viewHandler retourne, au format json deux ensemble (map) d'élément ( viewScreen et viewEntities), 
la première le/s affichage/s et la seconde pour les données.

Dans les futures versions, il sera surement faisable de ne souhaiter recevoir que la map de données.

=== ShowPortlet, ShowPortal
Le screen *showPortlet est redéfini* dans le POC (dans example/widget/example) par simplification, pour faire ce que 
l'on souhaite et seulement ça.

Il y a une uri showPortal dans l'exampleApi qui est dédié FrontJs.

=== Champ complémentaires
Ajout d'un champ dans l'entity PortalPagePortlet *watcherName* qui correspond au nom du watcher qui doit déclancher 
la mise à jour de la portlet 

include::poc-situation_fr.adoc[leveloffset=+1]

include::poc-todo_fr.adoc[leveloffset=+1]

include::poc-useCase_fr.adoc[leveloffset=+1]

include::poc-vuejs-details_fr.adoc[leveloffset=+1]

