////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= POC Vuejs Portal

Actuellement le premier applicatif javascript permettant d'utiliser les portlets - portal Apache OFBiz est écrit avec
le framework VueJs.

Il a été choisi pour sa simplicité d'apprentissage et en raison du pilotage de son développement par une communauté plutôt
que par une société.

== Installation POC VuejsPortal

. à partir d'un ofbiz-framework (trunk) téléchargé à partir du svn (https://ofbiz.apache.org/source-repositories.html[documentation standard  SourceRepository]) 
  une version svn supérieur à  1837232
. créer le répertoire plugins dans ofbiz-framework
. télécharger, avec git, dans le répertoire plugins :
.. le plugin vuejsportal à partir du https://gitlab.ofbizextra.org/ofbizextra/ofbizplugins/vuejsPortal
.. le plugin example (de Apache OFBiz) modifié pour les besoins du POC à partir de https://gitlab.ofbizextra.org/ofbizextra/ofbizplugins/example
    et en se mettant sur la branch vuejsPortal
. Il faut ensuite modifier quelques fichiers dans ofbiz-framework. +
  Pour se faire, executer la commande suivante en étant positionné dans le repertoire 'plugins/VuejsPortal' : +
  `rsync -a --exclude-from=./ofbizFiles/rsyncExcludes ./ofbizFiles/ ../../` +
. Pour le build de l'applicatif vuejs il faut avoir nodejs installé sur son environement
.. Pour installer node.js dans un environnement debian, executer le commandes suivantes : +
`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -` +
`sudo apt-get install -y nodejs` +
Dans le cas d'un autre environnement veuiller consulter la page https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
.. en attendant une commande intégré à gradle
.. il faut se positionner à la racine de la webapp vuejs 'plugins/vuejsPortal/webapp/vuejsPortal'
* `npm i`  <= pour charger toutes les dépendances
* `npm run build` <= pour builder
. il est maintenant possible de lancer ofbiz classiquement : +
`./gradlew cleanAll loadAll ofbiz` +
( à partir de la *racine de ofbiz-framework* )
. aller se connecter à l'application portal https://localhost:8443/exampleapi/control/main

== Choix pour le POC

Usage de la *branche trunk* de Apache OFBiz.

Usage des principes et architecture de *Portal Page et Portlet* de Apache OFBiz.

L'ensemble des exemples d'usage sont *avec le composant example* et pendant la durée du POC même des fichiers qui devrait
être dans common sont mis dans example afin de simplifier l'installation et mise à jours.

Une *webapp supplémentaire exampleapi* a été créé pour centraliser les uri autorisé pour le composant vuejsPortal, 
c'est paramétré dans le fichier constantes.js.

En attendant le login par token dans ofbiz (cf https://issues.apache.org/jira/browse/OFBIZ-9833 ) le login actuel dans 
le composant portal (  https://localhost:8443/exampleapi/control/login ) utilise le méchanisme *ofbiz standard de login via cookies* .

Les *screens, forms, menus* utilisés pour les portlets sont définis *en xml*.

Il y a *un composant (vuejs) par élément ofbiz* ( SingleItemRow => vue-single-item-row ).

Le *showPortlet est redéfini* dans le POC par simplification, pour faire ce que l'on souhaite et seulement ça.

include::poc-situation_fr.adoc[leveloffset=+1]

include::poc-todo_fr.adoc[leveloffset=+1]

include::poc-useCase_fr.adoc[leveloffset=+1]

