////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= POC Vuejs Portal

Actually the first javascript application enabling to use portlet system - portal Apache OFBiz is written with the Vue.js framework.

Vue.js has been choose for its easy learning curve and its community driven development instead of a corporation.

== POC VuejsPortal installation

. From a standard trunk ofbiz-framework with 1837232 version or superior (that can be downloaded at
https://ofbiz.apache.org/source-repositories.html[documentation standard  SourceRepository] using svn).
. Create the 'plugins' repository at ofbiz-framework root folder.
. In the plugins repository, download the 2 next repositories using git :
.. vuejsportal plugin that can be downloaded at https://gitlab.ofbizextra.org/ofbizextra/ofbizplugins/vuejsPortal
.. example plugin (by Apache OFBiz) which have been modified for the need of this POC, that can be downloaded at
https://gitlab.ofbizextra.org/ofbizextra/ofbizplugins/example on the `vuejsPortal` branch.
. After that you have to modify some files of ofbiz-framework. +
  Being located in the 'plugins/VuejsPortal' : +
  `./tools/applyOfbizFilesPatchs.sh` +
  And then copy some files +
  `rsync -a --exclude-from=./ofbizFiles/rsyncExcludes ./ofbizFiles/ ../../` +
. To be able to build the vue.js application you must have Node.js installed on your system.
.. To install Node.js on a debian based system, execute the following commands : +
  `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -` +
  `sudo apt-get install -y nodejs` +
  In case of another system, you can consult https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
.. Meanwhile an integrated gradle command
... Being located at 'plugins/vuejsPortal/webapp/vuejsPortal'
* `npm i` <= to install the project dependencies
* `npm run build` <= to build the project
. You can now launch OFBiz as regular : +
`./gradlew cleanAll loadAll ofbiz` +
(being located at the *root of ofbiz-framework* )
. You can now connect to the application portal at https://localhost:8443/exampleapi/control/main

== POC choices

Apache OFBiz *trunk branch* usage.

Principe and architecture of Apache OFBiz *Portal Page and Porlet* usage.

The whole use cases are applied *to example component* and during the the POC some new files used to be located in common
have been moved to example aiming to simplify the installation and update process.

An *additional webapp (exampleapi)* had been created to centralize allowed URIs for vuejsPortal component, which are listed
in constantes.js. +
vuejsPortal component is not bound to a component, it just need a base URI for send its requests.
This uri is temporary set in constantes.js but it will be more flexible later aiming to use vuejsPortal with multiple components

Portal component ( https://localhost:8443/exampleapi/control/login ) use *ofbiz standard login by cookies* mechanism, it will
later use ofbiz login by token (cf. https://issues.apache.org/jira/browse/OFBIZ-9833).

*screens, forms, menus* used for portlets are defined *with xml*, and dedicated files for better readability.

There is *a component (vuejs) for each ofbiz screen element* ( SingleItemRow => vue.single-item-row ), which are defined by
renderer for screen, form and menu ( and for html renderer that correspond globally to macro.ftl ). Actually, for the POC,
to list them, you can search for `output.*Screen(` .

=== XML tags used
During the POC, few new properties or XML tags had been added but some of existing tags and properties had been distorted
for an exclusive Vue.Js use.

* screen
  ** in `<container` tag
    *** `auto-update-target` is used to bind a `watcher` to a container.
    *** `id` is used to identify the container and enable to inject content into it with `setArea` later.
* form
  ** in `<on-event-update-area` tag (there can be many of them and they will be executed in xml apparition order. It will wait
      current task is completed before starting the next one. If any of these events is set, the submit button will prevent
      the form default behaviour, so if you need to post in addition to vuejsPortal feature you have to add an event-type `submit`)
    *** `event-type` +
      Define the action to be executed during the form submitting (click on submit button). It can take one of three next values :
      **** `setArea` update area with id `areaId` with the post result at URI `area-target` with included `parameter` elements.
      **** `setWatcher` update watcher `areaId` with included `parameter`. In case no parameter was passed to `setWatcher`
            it will use all form fields.
      **** `submit` will submit the form to `area-target` with provided `parameter` elements. Like `setArea` if no `parameter`
            are defined it will use the whole form. Error and success messages will be displayed.
  ** in `<on-field-event-update-area` tag (there can be many of them and they will be executed in xml apparition order. It will wait
      current task is completed before starting the next one.)
    *** `event-type` +
      Define the action to be executed during the form submitting (click on submit button). It can take one of four next values :
      **** `post` will post at URI `area-target` with the `parameter` elements included in the tag. If there are no parameters,
        it will use the whole form. It will display error and success messages.
      **** `setArea` update area identified by id `area-id` with the post result to URI `area-target` with included `parameter`
        elements. If no parameters was passed it will use the whole form.
      **** `setWatcher` update watcher with watcherName `area-id` with included `parameter` elements. If no parameters was
        passed it will use the whole form
      **** `setFieldInForm` will set the value of property `area-target` from form `area-id` to the actual field value.
  ** in `...-event-update-area` tag
    *** `auto-parameters-portlet` allow to automatically fill necessary portlet parameters :
      **** `portalPageId`
      **** `portalPortletId`
      **** `portletSeqId`
      **** `currentAreaId`
  ** in `<hyperlink` tag
    *** `link-type="anchor"` is used to make an internal call to FrontJs.
    *** `target-window` is used to design the watcherName that have to be updated.
* menu
  ** in `<link` tag
    *** `link-type="anchor"` is used to make an internal call to FrontJs.
    *** `target-window` is used to design the watcherName that have to be updated.

=== FrontJs Renderer
A *new viewHandler* and a new set of *renderer* had been created. +
A new package had been created in org.apache.ofbiz.widget.renderer named frontJs which contain all new renderer.

In this package, there is a new FrontJsOutput class which allow to construct necessary elements whit the wished format.
An object of this class is instantiate at the begin of viewHandler process, then is completed by rendered object call.

Uri *showPortletFj* of component exampleApi use the new viewHandler to return screen render result, showPortlet.

This URI is used by Vue.Js application for display information gathering. +
New viewHandle return a json which contain 2 maps ( viewScreen and viewEntities ). +
viewScreen contain all information about display.
viewEntities contain all information about data set.

In future revision, it would be only necessary to gather data set.

=== ShowPortlet, ShowPortal
*showPortlet* screen *is redefine* in this PAC ( in example/widget/example ) for simplification purpose, to only do what
we want.

there is a showPortal URI in FrontJs dedicated exampleApi.

=== Added field
A new field had been added to PortalPagePortlet entity : *watcherName* which is the name of the watcher that fire portlet update.

include::poc-situation_en.adoc[leveloffset=+1]

include::poc-todo_en.adoc[leveloffset=+1]

include::poc-useCase_en.adoc[leveloffset=+1]

include::poc-vuejs-details_en.adoc[leveloffset=+1]

