////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Situation actuel du POC

L'objectif est de faire fonctionner des pages portails correspondant à différent useCase. +
Au niveau du menu, il y a les différentes page, pour l'instant le nom de la page portail est ExampleFrontJs et ExampleFrontJs2. +
La première page contient 2 colonnes avec dans la première 2 portlets, le findExample puis le editExample et le listExample dans la seconde colonne. +
La seconde page se rapproche de la page Mgmnt avec 2 portlets par colonne.

Pour chacune de ces portlet un composant portlet est créé dans le front avec le nom de la portlet et celui-ci s'initialise
avec le showPortlet.

Le showPortletFj communique au composant la grappe de composants fils à créer ( ViewScreen ) et eventuellement le jeu de données nécessaire
à son utilisation ( ViewEntities ). +
Actuellement le format utilisé est json.

image::PortalPageDetail-Example.svg[Imbrication des container]

== ViewScreen et ViewEntities 
Actuellement tous les refresh d'écran (ou de portlet) font appel au FrontJsViewHandler qui renvoi la map ViewScreen et la map ViewEntities. +
Dans une logique client FrontJs, la map ViewScreen devrait être reçu uniquement la première fois, contrairement à la map ViewEntities qui 
contient les données.

Actuellement, la gestion des "use-when", quelque soit le niveau (screen, form, field, menu) est réalisé (dans OFBiz) au niveau de la gestion 
du modèle donc cette information n'est pas accessible dans les rendrerer. +
Dans le futur, il faudra transmettre au rendrer l'ensemble des éléments screens mais s'il y avait un use-when ajouter une données 
complémentaire boolean pour signaler qu'il faut l'afficher ou non. Ainsi, il sera possible lors des prochains appels à l'envoi de donnée
de transmettre le/s boolean en question avec la/es valeurs correspondantes, afin de pouvoir mettre à jours correctement l'écran final. 

