////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Les TODO restant du POC

== Mineurs

[IMPORTANT]
Ces TODO sont plutot dans l'ordre de priorité. Les premièrs étant les plus prioritaire et sont
sensés ne concerner que l'étapes majeur en cours (c'est à dire #pas# la suivante icon:smile-o[] )

---
Le screen showPortlet doit vérifier que les paramètre suivant sont bien présent, c'est nécessaire pour la lecture des attribues :

* portalPageId
* portalPortletId
* portletSeqId


---
Le *showPortlet* doit vérifier le respect de la *sécurité* par rapport au deux champs SecurityServiceName et SecurityMainAction.

== Majeurs

[IMPORTANT]
Normalement, il ne faut pas démarrer deux évolutions majeurs en paralléle, mais l'une après l'autre +
histoire d'avoir le temps de tester icon:smile-o[]. +
 +
Dans la suite, les Notes correspondent à des évolutions qui sont encore en discussion.


 ---
 
Pouvoir choisir facilement si une portlet s'étend en hauteur ou en largeur. Cas d'usage: portlet search, soit sur une colonne
soit en ligne.
 
A discuter, si la form doit inclure / géré les positions.





