////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Les TODO restant du POC

== Mineurs

[IMPORTANT]
Ces TODO sont plutot dans l'ordre de priorité. Les premièrs étant les plus prioritaire et sont
sensés ne concerner que l'étapes majeur en cours (c'est à dire #pas# la suivante icon:smile-o[] )

---
Le screen showPortlet doit vérifier que les paramètre suivant sont bien présent, c'est nécessaire pour la lecture des attribues :

* portalPageId
* portalPortletId
* portletSeqId


---
Lors de l'envoi d'un flux via showPortlet, il faut pouvoir *identifier l'entityName* des donnés afin de pouvoir créer
correctement la <<GENERICDADAVIEW GenericDataView>> au niveau du client Js.

---
*Une uri* permettant d'obtenir la liste des *noms de champ clés primaire pour une entityName* sera peut-être necessaire pour
permettre au client Js de vérifier l'uniticité d'un GenericDataView.

---
Le *showPortlet* doit vérifier le respect de la *sécurité* par rapport au deux champs SecurityServiceName et SecurityMainAction.

== Majeurs

[IMPORTANT]
Normalement, il ne faut pas démarrer deux évolutions majeurs en paralléle, mais l'une après l'autre +
histoire d'avoir le temps de tester icon:smile-o[]. +
 +
Dans la suite, les Notes correspondent à des évolutions qui sont encore en discussion.

---
L'ensemble des flux entre le serveur et le client Js sont en Json.

Grace à un nouveau Renderer (et donc un nouveau viewhandler) la construction de l'appel à une macro est remplacé
par la création d'un map contenant les paramètres de la macro. +
Dans cette map est ajouté le type de la macro (son nom dans le fichier template) et une map nommé context qui contient
les données (donc quasiment toujours un nom de champ et sa valeur) de ce champ.
 
 ---
 
Pouvoir choisir facilement si une portlet s'étend en hauteur ou en largeur. Cas d'usage: portlet search, soit sur une colonne
soit en ligne.
 
A discuter, si la form doit inclure / géré les positions.





