////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Situation actuel du POC

L'objectif est de faire fonctionner la page portail ExampleFrontJs qui contient 2 colonnes avec
dans la première 2 portlets, le findExample puis le editExample et le listExample dans la seconde colonne.

Pour chacune de ces portlet un composant portlet est créé dans le front avec le nom de la portlet et celui-ci s'initialise
avec le showPortlet.

Le showPortlet communique au composant la grappe de composants fils à créer ( ViewScreen ) et eventuellement le jeu de données nécessaire
à son utilisation ( ViewEntities ).

image::PortalPageDetail-Example.svg[Imbrication des container]


