////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= POC's remaining todos
This list contain only points which are already meet in use case process.

Most of time, each new use case (or portlet) give new task (ex: new field type not yet meet, or field properties not yet process)

== Minors

* review and change field-find to include title in the field to remove the "title" coloumn in find form
* Manage the ConfMod in the showPortalPage, to show (and manage) the portlet parameters page.
* Include header and footer in the VueJs application to have a full page manage by VueJs, and so have a complete Vue.Js look.
* Include all Common and Commonext part, like systemInfoNote

== Majeurs

* use VuejsRouter to be able to manage all screenType
* showPortletFj* must verify *security* about field SecurityServiceName and SecurityMainAction.





