
[[_portlet_category_example_portlet_type]]
= Catégorie EXAMPLE_PORTLET_TYPE, exemple à suivre

Cette catégorie de portlet regroupe toutes les portlets du composant Example, qui peuvent servir d'exemple.

[[_portlet_iconslist]]
== Liste des icônes utilisables dans les portlets

IconsList : Liste des icônes utilisables dans les portlets avec iconsPurpose et IconsTooltips_

Permet d'afficher toutes les icones référencées dans iconsPurpose, c'est un outil pour le développeur pour trouver la bonne icone en fonction de son.
besoin

=== Les paramètre de la Portlet

* aucun



=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_findexample]]
== Rechercher un exemple

FindExample : portlet (type Screenlet) de critères de recherche pour la liste des exemples

Portlet de recherche sur une entité, le resultat est affiché dans une autre portlet nomé ListExample

=== Les paramètre de la Portlet

* aucun



=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_listexample]]
== Liste des exemples

ListExample : portlet (type ScreenletList) listant des exemples selon les critères de recherche fournis par une portlet de recherche (ici FindExample)

Portlet de liste sur une entité, cette liste est filtré en fonction des critère de recherche indiqué dans la portlet FindExample.
Cette portlet de liste contient 2 liens, l'un vers une autre portlet dans la même page et l'autre vers une autre page portail.

Le lien vers l'affichage de la portlet de résumé, utilise l'option du show-portlet qui permet de refermer la portlet de liste quand il est clické.
L'utilisateur peut la ré-ouvrir sans relancer la recherche.

=== Les paramètre de la Portlet

usage de GenericRecapPageParam pour le formulaire d'édition de paramètre 

* recapPageId : correspond à l'identifiant de la page portail qui sera ouverte via le lien de l'icone "Page récapitulative" pour chaque item de la liste.


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_exampledetailsmenu]]
== Résumé et menus associés pour un exemple (DetailsMenu)

ExampleDetailsMenu : portlet(type Screenlet) de résumé et menus liés à un exemple, et utilisant une portlet de contener de détails (ici ExampleDetail)

Portlet d'affichage du résumé d'un exemple (un objet métier) avec un menu permettant d'afficher l'ensemble des détails de l'exemple en question.
Chacune des options du menu affiche la portlet correspondante, toujours dans le même lieu de la  page portail.

Cette portlet utilise l'attribue pkIdName, donc elle ne s'affiche pas si elle ne reçoit pas un exempleId.
C'est pour ça qu'elle n'apparait que suite au click sur un lien de la liste des exemples

=== Les paramètre de la Portlet

* aucun


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_exampledetail]]
== Contener utilisé pour afficher des portlets de détails pour un exemple

ExampleDetail : portlet (type Empty) servant de contener aux portlets de détails d'un exemple (commandé par le menu de la portlet ExampleDetailsMenu)

Portlet ultra simple, son utilité est juste de définir où s'afficheront les portlet de detail quand on click sur une option du menu de la portlet ExampleDetailMenu.

=== Les paramètre de la Portlet

* aucun


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_showexample]]
== Montrer un exemple (tous les champs)

ShowExample : portlet (type Screenlet) de visualisation/modification d'une entité majeure (ici, exemple)

Affichage de la synthèse d'un exemple (un objet métier), l'ojectif est de montrer l'ensemble des informations  importantes lié à un exemple, la  plupart des champs de exemple et pourquoi pas certain élément des entités lié.

En mode édition, seul les champs de l'entité exemple seront modifiable.

=== Les paramètre de la Portlet

* aucun


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_createexample]]
== Créer un exemple

CreateExample : portlet (type Screenlet) de création d'un exemple et ses entités secondaires

Portlet permettant la création d'un exemple.

=== Les paramètre de la Portlet

* aucun


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_exampleitems]]
== Listes des lignes d'exemple

ExampleItems : portlet (type ScreenletList) de gestion des lignes d'un exemple (affiche la liste et le menu)

Portlet permettant l'affichage et la gestion -création, modification, suppression- des lignes d'un exemple.

Cette portlet utilise l'attribue pkIdName="exampleId", donc elle ne s'affiche pas si elle ne reçoit pas un exampleId.
C'est pour ça qu'elle n'apparait que suite à la sélection d'un exemple, dans la page portail récapitulative d'un exemple.

=== Les paramètre de la Portlet

usage de GenericEditEditOrShowParam pour le formulaire d'édition de paramètre 

* showEditButton : Y ou N, affiche ou non le boutton d'édition d'une ligne d'exemple.
* showScreenletMenu : Y ou N, affiche ou non le menu d'édition dand le champ titre de la portlet.


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_examplestatus]]
== Liste des statuts de l'exemple

ExampleStatus : Liste tous les (évolution de) statuts de l'exemple (portlet utilisant un modéle de portlet et showPortlet)

Portlet permettant l'affichage et la gestion -création, modification, suppression- de l'historique de changement de statut de l'exemple.

Cette portlet utilise l'attribue pkIdName="exampleId", donc elle ne s'affiche pas si elle ne reçoit pas un exampleId.
C'est pour ça qu'elle n'apparait que suite à la sélection d'un exemple, dans la page portail récapitulative d'un exemple.

=== Les paramètre de la Portlet

usage de GenericEditEditOrShowParam pour le formulaire d'édition de paramètre 

* showEditButton : Y ou N, affiche ou non le boutton d'édition d'une ligne d'exemple.
* showScreenletMenu : Y ou N, affiche ou non le menu d'édition dand le champ titre de la portlet.


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_examplefeatureappls]]
== Association de caractéristiques à un exemple

ExampleFeatureAppls : portlet listant les associations de caractéristiques d'exemple  (type Screenlet, bien qu'utilisant une liste, pour pouvoir ajouter un menu externe)

Portlet permettant l'affichage et la gestion des liens -création, modification, suppression- entre l'exemple et un ensemble de caractèristique d'exemple.

Cette portlet utilise l'attribue pkIdName="exampleId", donc elle ne s'affiche pas si elle ne reçoit pas un exampleId.
C'est pour ça qu'elle n'apparait que suite à la sélection d'un exemple, dans la page portail récapitulative d'un exemple.

=== Les paramètre de la Portlet

usage de GenericEditEditOrShowParam pour le formulaire d'édition de paramètre 

* showEditButton : Y ou N, affiche ou non le boutton d'édition d'une ligne d'exemple.
* showScreenletMenu : Y ou N, affiche ou non le menu d'édition dand le champ titre de la portlet.


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_findexamplefeature]]
== Rechercher des caractéristiques d'exemple

FindExampleFeature : portlet (type Screenlet) de critères de recherche pour la liste des caractéristiques d'exemple

Portlet de recherche sur l'entité caractèristique d'exemple.

=== Les paramètre de la Portlet

* aucun


=== Règles de Securité

* aucune, (celles du composant)


[[_portlet_listexamplefeature]]
== Liste les caractéristiques d'exemple

ListExampleFeature : portlet (type ScreenletList) listant des caractéristique d'exemples selon les critères de recherche fournis par une portlet de recherche (ici FindExampleFeature)

Portlet de Liste sur l'entité caractèristique d'exemple.

=== Les paramètre de la Portlet

* aucun


=== Règles de Securité

* aucune, (celles du composant)
