
[[_portlet_category_example]]
= Catégorie EXAMPLE, ancienne

Cette catégorie de portlet regroupe les portlets du composant Example, qui pouvait servir d'exemple avant que les portlets  avec "Type de portlet" apparaissent.

[[_portlet_example_1]]
== Example 1

EXAMPLE_1 : Example portlet n.1


Portlet très simple pour montrer : 

* l'association entre un screen et une portlet
* l'usage de paramètres de portlet.


=== Les paramètre de la Portlet

* ItemsToShow, non vide choisir une valeur parmi 5,10,15,20,25,30,35. Uniquement à titre de démonstration de paramètre à valeur multiple. ce paramètre n'est pas utilisé dans la portlet
* SpecificTitle, C'est le libéllé qui apparait dans la portlet s'il est saisi.


=== Règles de Securité

* aucune, (celles du composant)


=== Remarques Techniques

Portlet de OFBiz de base, pas d'usage de "Type de portlet" et sans usage de show-portlet (ajax)

[[_portlet_example_2]]
== Example 2

EXAMPLE_2 : Example portlet n.2


Portlet très simple pour montrer : 

* l'association entre un screen et une portlet
* l'usage d'un paramètre de portlet pour influencer un lien.


=== Les paramètre de la Portlet

* nextPortalPageId : si ce paramètre est non vide alors la portlet afficher un lien vers cette page  portail (avec comme paramètre complémentaire le paramètre suivant nextParentPortalPageId)
* nextParentPortalPageId : cf ci-dessus


=== Règles de Securité

* aucune, (celles du composant)


=== Remarques Techniques

Portlet de OFBiz de base, pas d'usage de "Type de portlet" et sans usage de show-portlet (ajax)

[[_portlet_example_3]]
== Example 3

EXAMPLE_3 : Example portlet n.3

Portlet très simple pour montrer : 

* l'association entre un screen et une portlet
* l'usage de paramètre très basique.


=== Les paramètre de la Portlet

* SpecificTitle : s'affiche dans la portlet
* SpecificSubTitle :  s'affiche dans la portlet


=== Règles de Securité

* aucune, (celles du composant)


=== Remarques Techniques

Portlet de OFBiz de base, pas d'usage de "Type de portlet" et sans usage de show-portlet (ajax)