import {
  mdiArrowCollapse,
  mdiArrowExpand,
  mdiArrowCollapseUp,
  mdiArrowExpandDown,
  mdiArrowCollapseLeft,
  mdiArrowCollapseRight,
  mdiArrowLeft,
  mdiArrowRight,
  mdiDotsVertical,
  mdiViewList,
  mdiFormatListBulleted,
  mdiPuzzle,
  mdiTimetable,
  mdiPlusCircle,
  mdiDelete,
  mdiThemeLightDark,
  mdiClose,
  mdiPalette,
  mdiSync,
  mdiPencil,
  mdiCheck,
  mdiPhone,
  mdiEmail,
  mdiDesktopTower,
  mdiAt,
  mdiFileCloud,
  mdiMapMarker,
  mdiNoteText,
  mdiWeb,
  mdiServer,

} from '@mdi/js'

export default {
  'mdi-arrow-collapse': mdiArrowCollapse,
  'mdi-arrow-expand': mdiArrowExpand,
  'mdi-arrow-collapse-up': mdiArrowCollapseUp,
  'mdi-arrow-expand-down': mdiArrowExpandDown,
  'mdi-arrow-collapse-left': mdiArrowCollapseLeft,
  'mdi-arrow-collapse-right': mdiArrowCollapseRight,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-view-list': mdiViewList,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-puzzle': mdiPuzzle,
  'mdi-timetable': mdiTimetable,
  'mdi-plus-circle': mdiPlusCircle,
  'mdi-delete': mdiDelete,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-close': mdiClose,
  'mdi-palette': mdiPalette,
  'mdi-sync': mdiSync,
  'mdi-pencil': mdiPencil,
  'mdi-check': mdiCheck,
  'mdi-phone': mdiPhone,
  'mdi-email': mdiEmail,
  'mdi-desktop-tower': mdiDesktopTower,
  'mdi-at': mdiAt,
  'mdi-file-cloud': mdiFileCloud,
  'mdi-map-marker': mdiMapMarker,
  'mdi-note-text': mdiNoteText,
  'mdi-text': mdiWeb,
  'mdi-server': mdiServer,

};
