////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Apache OFBiz Screenlet Reference
The Apache OFBiz Project
Release 17.12
:imagesdir: ./images
ifdef::backend-pdf[]
:title-logo-image: image::OFBiz-Logo.svg[Apache OFBiz Logo, pdfwidth=4.25in, align=center]
:source-highlighter: rouge
endif::[]

== Introduction to OFBiz
Welcome to _Apache OFBiz_! A powerful top level Apache software project.
OFBiz is an Enterprise Resource Planning (ERP) System written in Java and
houses a large set of libraries, entities, services and features to run
all aspects of your business.

This manual will describe all screenlet available to manage business object.
Most of the OFBiz GUI is design by assembling some screenlet for one page. +
One of the configuration / personalisation task could be to choose its own assemblage.

If you need to understand the process and bussiness object for the core application of this framework like the
Party Manager, Order Manager, Accounting system, and others you should read the "Apache OFBiz Developer Manual".

If you wish to contribute to OFBiz and help make it better, you may wish to read
the "Apache OFBiz Developer Manual" for a deeper understanding of the
architectural concepts of the framework.


=== Core Business Applications
Most businesses share universal needs. They require accounting functionality,
managing customers, placing orders, book-keeping, invoicing and so on.

OFBiz is designed so that such basic universal business needs are available
through a set of core business applications. These applications all share a
unified data-model with a set of unified services to implement this
functionality.

Each core business application contain a group of screenlet, this documentation will help you
to find and understand which one do what

All screenlet are organize by Category, so there is one chapter by category. 

include::../../plugins/partymgrfjs/src/docs/asciidoc/screenlet-party-profile.adoc[leveloffset=+1]

