export default {
  apiUrl: 'https://localhost:8443/exampleapi/control',
  formApiUrl: 'https://localhost:8443/example/control',
  hostUrl: 'https://localhost:8443',
  main: {path: '/main', tokenRequired: false},
  login: {path: '/login', tokenRequired: false},
  ping: {path: '/ping', tokenRequired: false},
  ajaxCheckLogin: {path: '/ajaxCheckLogin', tokenRequired: false},
  portalPageDetail: {path: '/portalPageDetail', tokenRequired: false},
  showPortlet: {path: '/exampleapi/control/showPortletFj', tokenRequired: false},

  components: {
    Form: 'vue-form',
    ListWrapper: 'vue-list-wrapper',
    Header: 'vue-header',
    HeaderRow: 'vue-header-row',
    HeaderRowCell: 'vue-header-row-cell',
    HeaderRowFormCell: 'vue-header-row-form-cell',
    ItemRow: 'vue-item-row',
    ItemRowCell: 'vue-item-row-cell',
    ItemRowFormCell: 'vue-item-row-form-cell',
    SingleWrapper: 'vue-single-wrapper',
    FieldRow: 'vue-field-row',
    FieldRowTitleCell: 'vue-field-row-title-cell',
    FieldRowWidgetCell: 'vue-field-row-widget-cell',
    FieldGroup: '?', // todo
    FieldTitle: 'vue-field-title',
    TextField: 'vue-text-field',
    TextAreaField: 'vue-text-area-field',
    DisplayField: 'vue-display-field',
    DateTimeField: 'vue-date-time-field',
    TextFindField: 'vue-text-find-field',
    DropDownField: 'vue-drop-down-field',
    RadioField: 'vue-radio-field',
    HiddenField: 'vue-hidden-field',
    HyperlinkTitle: 'vue-hyperlink-title',
    HyperlinkField: 'vue-hyperlink-field',
    SubmitField: 'vue-submit-field',
    NextPrev: 'vue-next-prev',
    SortField: 'vue-sort-field',
    Screenlet: 'vue-screenlet',
    ScreenletSubWidget: 'vue-screenlet-sub-widget',
    Menu: 'vue-menu',
    MenuItem: 'vue-menu-item',
    Link: 'vue-link',
    Container: 'vue-container'
  }
}
